services:
  - type: web
    name: ailign-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --timeout 180 --workers 2 --log-level debug
    plan: free
    healthCheckPath: /health
    healthCheckTimeout: 10000
    envVars:
      - key: LYZR_API_KEY
        value: sk-default-4nIJzEOtOeXpFjIu3U9wDyUD5U4V49h4
      - key: LYZR_AGENT_ID
        value: 683d10bb3b7c57f1745cfaf9
      - key: LYZR_USER_ID
        value: pavansharadha@gmail.com
      - key: LYZR_SESSION_ID
        value: 683d10bb3b7c57f1745cfaf9-e0fqnfekgs
      - key: GEMINI_API_KEY
        value: AIzaSyARVFZ6ub0Q6vfJATOLg1ew4TrNlJiL9vE
      - key: PORT
        value: 10000 